services:
  app:
    container_name: app,
    restart: always,
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env.production
    expose:
      - 4000:4000
    networks:
      app-network:
        ipv4_address: 192.168.100.50
  db:
    container_name: db
    restart: always,
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DB=socialmedia
    networks:
      app-network:
        ipv4_address: 192.168.100.60

networks:

volumes:
