CREATE DATABASE IF NOT EXISTS socialmedia;

USE socialmedia;

CREATE TABLE IF NOT EXISTS users {
    id INT PRIMARY KEY AUTO_INCREMENT,
    nama VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
}

CREATE TABLE IF NOT EXISTS posts {
    id INT PRIMARY KEY AUTO_INCREMENT,
    userId INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
    FOREIGN KEY (userId) REFERENCES users(id)
        ON DELETE CASCADE   
        ON UPDATE CASCADE
}

CREATE TABLE IF NOT EXISTS comments {
    id INT PRIMARY KEY AUTO_INCREMENT,
    userId INT NOT NULL,
    postId INT NOT NULL,
    comment TEXT,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES users(id)
        ON DELETE CASCADE   
        ON UPDATE CASCADE
    FOREIGN KEY (postId) REFERENCES posts(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
}